// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: fetch_record.proto

// The fetch-record wire format. A fetch job serialises one FetchMessage
// per window, marshals it to binary protobuf, zstd-compresses it, and
// writes it to the output bucket as
//   output/<YYYY-MM-DD>/<window-key>.binpb.zst
//
// This schema is vendored from the canonical Lovelace fetcher. The
// elemental ingest path consumes exactly this shape, so **field numbers
// and types must not be changed** — the binary wire format is defined by
// field numbers, not message or package names. The package name and
// go_package below are deliberately fido-local (not the upstream import
// path) so this repo stays self-contained; that rename does not affect
// wire compatibility.

package fetchrecord

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Whether a schema element should be clustered with similar elements.
type Mergeability int32

const (
	Mergeability_MERGEABILITY_UNSPECIFIED   Mergeability = 0
	Mergeability_MERGEABILITY_MERGEABLE     Mergeability = 1 // Run through resolution clustering
	Mergeability_MERGEABILITY_NOT_MERGEABLE Mergeability = 2 // Deterministic lookup, no clustering
)

// Enum value maps for Mergeability.
var (
	Mergeability_name = map[int32]string{
		0: "MERGEABILITY_UNSPECIFIED",
		1: "MERGEABILITY_MERGEABLE",
		2: "MERGEABILITY_NOT_MERGEABLE",
	}
	Mergeability_value = map[string]int32{
		"MERGEABILITY_UNSPECIFIED":   0,
		"MERGEABILITY_MERGEABLE":     1,
		"MERGEABILITY_NOT_MERGEABLE": 2,
	}
)

func (x Mergeability) Enum() *Mergeability {
	p := new(Mergeability)
	*p = x
	return p
}

func (x Mergeability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mergeability) Descriptor() protoreflect.EnumDescriptor {
	return file_fetch_record_proto_enumTypes[0].Descriptor()
}

func (Mergeability) Type() protoreflect.EnumType {
	return &file_fetch_record_proto_enumTypes[0]
}

func (x Mergeability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mergeability.Descriptor instead.
func (Mergeability) EnumDescriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{0}
}

// Schema-level metadata for a single element (flavor, property,
// relationship, or attribute). Carried once per unique element in the
// FetchMessage's metadata maps rather than duplicated on every
// ResolverInformation instance.
// Next ID: 3
type SchemaElementMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema description (e.g., "Annual revenue as reported in financial
	// filings"). From the dataset or system schema's description field.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Human-friendly display name (e.g., "Annual Revenue" for property
	// "annual_revenue"). From the dataset or system schema's display_name field.
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaElementMeta) Reset() {
	*x = SchemaElementMeta{}
	mi := &file_fetch_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaElementMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaElementMeta) ProtoMessage() {}

func (x *SchemaElementMeta) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaElementMeta.ProtoReflect.Descriptor instead.
func (*SchemaElementMeta) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaElementMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaElementMeta) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// The durable storage of extracted information from a data source.
// Next ID: 11
type FetchMessage struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Records                  []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	WindowCompleteUnixMicros int64                  `protobuf:"varint,2,opt,name=window_complete_unix_micros,json=windowCompleteUnixMicros,proto3" json:"window_complete_unix_micros,omitempty"` // ignore this value if <= 0
	// The "citation" field contains a reference to the raw data for
	// records in this message (e.g., a source doc's URI). This is
	// source-specific in its semantics.
	//
	// ****************************************************************
	// NOTE: This is not to be confused with the Citation message
	// used elsewhere in the proto!!!
	// ****************************************************************
	Citation string `protobuf:"bytes,3,opt,name=citation,proto3" json:"citation,omitempty"`
	// Unix epoch microseconds of when the source data from which the FetchMessage derived was downloaded.
	SourceDownloadTimestamp int64 `protobuf:"varint,4,opt,name=source_download_timestamp,json=sourceDownloadTimestamp,proto3" json:"source_download_timestamp,omitempty"`
	// Schema metadata for elements referenced in this FetchMessage. Each map
	// contains only elements actually present in the records — not the full
	// schema. Keys are qualified names (e.g., "sec_10k::debt_ratio" for a
	// namespaced property).
	//
	// Flavor metadata keyed by qualified flavor name (e.g., "company",
	// "schema::flavor::event").
	FlavorMetadata map[string]*SchemaElementMeta `protobuf:"bytes,5,rep,name=flavor_metadata,json=flavorMetadata,proto3" json:"flavor_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Property metadata keyed by qualified property name (e.g.,
	// "annual_revenue", "schema::property::event_category").
	PropertyMetadata map[string]*SchemaElementMeta `protobuf:"bytes,6,rep,name=property_metadata,json=propertyMetadata,proto3" json:"property_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Relationship metadata keyed by qualified relationship name (e.g.,
	// "head_of", "appears_in", "schema::relationship::participant").
	RelationshipMetadata map[string]*SchemaElementMeta `protobuf:"bytes,7,rep,name=relationship_metadata,json=relationshipMetadata,proto3" json:"relationship_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Attribute metadata keyed by scoped attribute name
	// ("{qualifiedProperty}::{attrName}", e.g., "appears_in::source",
	// "schema::relationship::participant::role").
	AttributeMetadata map[string]*SchemaElementMeta `protobuf:"bytes,8,rep,name=attribute_metadata,json=attributeMetadata,proto3" json:"attribute_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Who produced this FetchMessage. For manual bandaids (e.g.
	// undermerge-fix), this is the operator's email entered in the UI.
	// Empty for automated fetch pipelines.
	Author string `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	// Free-form operator notes explaining why this message was produced
	// (e.g., the justification for an undermerge-fix). Human-readable
	// commentary only — this is NOT a citation / source URI. For that,
	// see the `citation` field above.
	Notes         string `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMessage) Reset() {
	*x = FetchMessage{}
	mi := &file_fetch_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessage) ProtoMessage() {}

func (x *FetchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessage.ProtoReflect.Descriptor instead.
func (*FetchMessage) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{1}
}

func (x *FetchMessage) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *FetchMessage) GetWindowCompleteUnixMicros() int64 {
	if x != nil {
		return x.WindowCompleteUnixMicros
	}
	return 0
}

func (x *FetchMessage) GetCitation() string {
	if x != nil {
		return x.Citation
	}
	return ""
}

func (x *FetchMessage) GetSourceDownloadTimestamp() int64 {
	if x != nil {
		return x.SourceDownloadTimestamp
	}
	return 0
}

func (x *FetchMessage) GetFlavorMetadata() map[string]*SchemaElementMeta {
	if x != nil {
		return x.FlavorMetadata
	}
	return nil
}

func (x *FetchMessage) GetPropertyMetadata() map[string]*SchemaElementMeta {
	if x != nil {
		return x.PropertyMetadata
	}
	return nil
}

func (x *FetchMessage) GetRelationshipMetadata() map[string]*SchemaElementMeta {
	if x != nil {
		return x.RelationshipMetadata
	}
	return nil
}

func (x *FetchMessage) GetAttributeMetadata() map[string]*SchemaElementMeta {
	if x != nil {
		return x.AttributeMetadata
	}
	return nil
}

func (x *FetchMessage) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FetchMessage) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// A strong identifier that uniquely identifies an entity. The property must
// be declared as a strong ID property in the dataset schema. The value is the
// identifier itself (e.g., a CIK number, an accession number).
// Next ID: 3
type StrongID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Property      string                 `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"` // e.g., "company_cik", "accession_number"
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`       // e.g., "0000320193", "0000320193-24-000123"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrongID) Reset() {
	*x = StrongID{}
	mi := &file_fetch_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrongID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrongID) ProtoMessage() {}

func (x *StrongID) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrongID.ProtoReflect.Descriptor instead.
func (*StrongID) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{2}
}

func (x *StrongID) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *StrongID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Citation information.
// Next ID: 5
type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Explanation   string                 `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	PageNumber    int64                  `protobuf:"varint,4,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_fetch_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{3}
}

func (x *Citation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Citation) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *Citation) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Citation) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

// Next ID: 5
type ResolverInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether or not the entity associated with this resolver information can
	// be clustered with other entities.
	Mergeability Mergeability `protobuf:"varint,1,opt,name=mergeability,proto3,enum=fetchrecord.Mergeability" json:"mergeability,omitempty"`
	// Contextual snippets for entity resolution, positionally aligned to names:
	//
	//	snippets[0]   → ProtoEntity.name
	//	snippets[1..] → aliases[0..n-1]
	//
	// If fewer snippets than names+aliases, the last snippet is repeated for
	// remaining names. If more snippets than names+aliases, extra snippets are
	// dropped. Empty names that were filtered still consume their snippet slot
	// (i.e., positional alignment is preserved regardless of filtering).
	Snippets []string `protobuf:"bytes,2,rep,name=snippets,proto3" json:"snippets,omitempty"`
	// Explicit strong ID declarations. Each entry is a property-value pair
	// (e.g., {property: "company_cik", value: "0000320193"}). Multiple strong
	// IDs can be declared per entity (e.g., both CIK and EIN).
	StrongIds []*StrongID `protobuf:"bytes,3,rep,name=strong_ids,json=strongIds,proto3" json:"strong_ids,omitempty"`
	// Alternative names for the entity, positionally aligned to snippets[1..].
	// See snippets field for the mapping contract.
	Aliases       []string `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolverInformation) Reset() {
	*x = ResolverInformation{}
	mi := &file_fetch_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolverInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverInformation) ProtoMessage() {}

func (x *ResolverInformation) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverInformation.ProtoReflect.Descriptor instead.
func (*ResolverInformation) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{4}
}

func (x *ResolverInformation) GetMergeability() Mergeability {
	if x != nil {
		return x.Mergeability
	}
	return Mergeability_MERGEABILITY_UNSPECIFIED
}

func (x *ResolverInformation) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *ResolverInformation) GetStrongIds() []*StrongID {
	if x != nil {
		return x.StrongIds
	}
	return nil
}

func (x *ResolverInformation) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// A unified representation of an entity, used for both the record subject
// (entity A) and relationship targets (entity B). Replaces the old pattern
// of separate fields on Record and Target, and eliminates TargetIdentifier.
// Next ID: 10
type ProtoEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable entity name. Never overloaded as a strong ID value.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The flavor (entity type) of this entity.
	Flavor string `protobuf:"bytes,2,opt,name=flavor,proto3" json:"flavor,omitempty"`
	// Citation information for the entity.
	Citations []*Citation `protobuf:"bytes,7,rep,name=citations,proto3" json:"citations,omitempty"`
	// Contextual information for named entity resolution.
	NamedEntityResolverInformation *ResolverInformation `protobuf:"bytes,8,opt,name=named_entity_resolver_information,json=namedEntityResolverInformation,proto3" json:"named_entity_resolver_information,omitempty"`
	// Contextual information for flavor resolution.
	FlavorResolverInformation *ResolverInformation `protobuf:"bytes,9,opt,name=flavor_resolver_information,json=flavorResolverInformation,proto3" json:"flavor_resolver_information,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ProtoEntity) Reset() {
	*x = ProtoEntity{}
	mi := &file_fetch_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoEntity) ProtoMessage() {}

func (x *ProtoEntity) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoEntity.ProtoReflect.Descriptor instead.
func (*ProtoEntity) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoEntity) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *ProtoEntity) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *ProtoEntity) GetNamedEntityResolverInformation() *ResolverInformation {
	if x != nil {
		return x.NamedEntityResolverInformation
	}
	return nil
}

func (x *ProtoEntity) GetFlavorResolverInformation() *ResolverInformation {
	if x != nil {
		return x.FlavorResolverInformation
	}
	return nil
}

// A collection of atoms, all regarding the same entity.
// Each record comes from a distinct report from the data source.
// Next ID: 8
type Record struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// When the source material was published. Unix epoch microseconds.
	// For example, the publication date of a news article or the filing date of
	// an SEC document. Distinct from Atom.timestamp, which records when an
	// individual fact within the source occurred (which may be earlier).
	// Fetch/download time is not recorded here — it is captured in the
	// timestamps of files written to disk.
	Timestamp int64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Atoms     []*Atom `protobuf:"bytes,4,rep,name=atoms,proto3" json:"atoms,omitempty"`
	// The subject entity (entity A) of this record. All identity information
	// (name, flavor, resolver information, strong IDs) lives here.
	Subject       *ProtoEntity `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_fetch_record_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{6}
}

func (x *Record) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Record) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Record) GetAtoms() []*Atom {
	if x != nil {
		return x.Atoms
	}
	return nil
}

func (x *Record) GetSubject() *ProtoEntity {
	if x != nil {
		return x.Subject
	}
	return nil
}

// A piece of information about an entity.
// Next ID: 18
type Atom struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The property or relationship being asserted.
	Property string `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Atom_FloatVal
	//	*Atom_StrVal
	//	*Atom_Target
	Value      isAtom_Value `protobuf_oneof:"value"`
	Attributes []*Attribute `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// When the individual fact occurred. Unix epoch microseconds. This may differ
	// from Record.timestamp (the source publication date) when the source
	// retrospectively mentions past events.
	//
	// Use the most specific time available:
	//   - If the fact has an explicit date, use it (e.g., "FY2023 revenue" → 2023-01-01).
	//   - Otherwise, use the source publication date (i.e., copy Record.timestamp).
	//   - Must always be set; never leave as zero.
	Timestamp int64 `protobuf:"varint,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Citation information for the atom.
	Citations []*Citation `protobuf:"bytes,16,rep,name=citations,proto3" json:"citations,omitempty"`
	// Contextual information for property and relationship resolution.
	PropertyResolverInformation *ResolverInformation `protobuf:"bytes,17,opt,name=property_resolver_information,json=propertyResolverInformation,proto3" json:"property_resolver_information,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Atom) Reset() {
	*x = Atom{}
	mi := &file_fetch_record_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Atom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Atom) ProtoMessage() {}

func (x *Atom) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Atom.ProtoReflect.Descriptor instead.
func (*Atom) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{7}
}

func (x *Atom) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *Atom) GetValue() isAtom_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Atom) GetFloatVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*Atom_FloatVal); ok {
			return x.FloatVal
		}
	}
	return 0
}

func (x *Atom) GetStrVal() string {
	if x != nil {
		if x, ok := x.Value.(*Atom_StrVal); ok {
			return x.StrVal
		}
	}
	return ""
}

func (x *Atom) GetTarget() *ProtoEntity {
	if x != nil {
		if x, ok := x.Value.(*Atom_Target); ok {
			return x.Target
		}
	}
	return nil
}

func (x *Atom) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Atom) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Atom) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *Atom) GetPropertyResolverInformation() *ResolverInformation {
	if x != nil {
		return x.PropertyResolverInformation
	}
	return nil
}

type isAtom_Value interface {
	isAtom_Value()
}

type Atom_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,4,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type Atom_StrVal struct {
	StrVal string `protobuf:"bytes,5,opt,name=str_val,json=strVal,proto3,oneof"`
}

type Atom_Target struct {
	// The target entity (entity B) of a relationship. Uses ProtoEntity,
	// the same message type as Record.subject, so subjects and targets
	// are described identically.
	Target *ProtoEntity `protobuf:"bytes,12,opt,name=target,proto3,oneof"`
}

func (*Atom_FloatVal) isAtom_Value() {}

func (*Atom_StrVal) isAtom_Value() {}

func (*Atom_Target) isAtom_Value() {}

// An attribute of an atom.
// Next ID: 9
type Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The attribute name (e.g., "unit", "fiscal_year", "filing_type").
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to TypedValue:
	//
	//	*Attribute_FloatValue
	//	*Attribute_StrValue
	TypedValue isAttribute_TypedValue `protobuf_oneof:"typed_value"`
	// Contextual information for attribute resolution.
	AttributeResolverInformation *ResolverInformation `protobuf:"bytes,8,opt,name=attribute_resolver_information,json=attributeResolverInformation,proto3" json:"attribute_resolver_information,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_fetch_record_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_record_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_fetch_record_proto_rawDescGZIP(), []int{8}
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetTypedValue() isAttribute_TypedValue {
	if x != nil {
		return x.TypedValue
	}
	return nil
}

func (x *Attribute) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.TypedValue.(*Attribute_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Attribute) GetStrValue() string {
	if x != nil {
		if x, ok := x.TypedValue.(*Attribute_StrValue); ok {
			return x.StrValue
		}
	}
	return ""
}

func (x *Attribute) GetAttributeResolverInformation() *ResolverInformation {
	if x != nil {
		return x.AttributeResolverInformation
	}
	return nil
}

type isAttribute_TypedValue interface {
	isAttribute_TypedValue()
}

type Attribute_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Attribute_StrValue struct {
	StrValue string `protobuf:"bytes,5,opt,name=str_value,json=strValue,proto3,oneof"`
}

func (*Attribute_FloatValue) isAttribute_TypedValue() {}

func (*Attribute_StrValue) isAttribute_TypedValue() {}

var File_fetch_record_proto protoreflect.FileDescriptor

const file_fetch_record_proto_rawDesc = "" +
	"\n" +
	"\x12fetch_record.proto\x12\vfetchrecord\"X\n" +
	"\x11SchemaElementMeta\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"\x9a\b\n" +
	"\fFetchMessage\x12-\n" +
	"\arecords\x18\x01 \x03(\v2\x13.fetchrecord.RecordR\arecords\x12=\n" +
	"\x1bwindow_complete_unix_micros\x18\x02 \x01(\x03R\x18windowCompleteUnixMicros\x12\x1a\n" +
	"\bcitation\x18\x03 \x01(\tR\bcitation\x12:\n" +
	"\x19source_download_timestamp\x18\x04 \x01(\x03R\x17sourceDownloadTimestamp\x12V\n" +
	"\x0fflavor_metadata\x18\x05 \x03(\v2-.fetchrecord.FetchMessage.FlavorMetadataEntryR\x0eflavorMetadata\x12\\\n" +
	"\x11property_metadata\x18\x06 \x03(\v2/.fetchrecord.FetchMessage.PropertyMetadataEntryR\x10propertyMetadata\x12h\n" +
	"\x15relationship_metadata\x18\a \x03(\v23.fetchrecord.FetchMessage.RelationshipMetadataEntryR\x14relationshipMetadata\x12_\n" +
	"\x12attribute_metadata\x18\b \x03(\v20.fetchrecord.FetchMessage.AttributeMetadataEntryR\x11attributeMetadata\x12\x16\n" +
	"\x06author\x18\t \x01(\tR\x06author\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x1aa\n" +
	"\x13FlavorMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.fetchrecord.SchemaElementMetaR\x05value:\x028\x01\x1ac\n" +
	"\x15PropertyMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.fetchrecord.SchemaElementMetaR\x05value:\x028\x01\x1ag\n" +
	"\x19RelationshipMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.fetchrecord.SchemaElementMetaR\x05value:\x028\x01\x1ad\n" +
	"\x16AttributeMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.fetchrecord.SchemaElementMetaR\x05value:\x028\x01\"<\n" +
	"\bStrongID\x12\x1a\n" +
	"\bproperty\x18\x01 \x01(\tR\bproperty\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"y\n" +
	"\bCitation\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1f\n" +
	"\vpage_number\x18\x04 \x01(\x03R\n" +
	"pageNumber\"\xc0\x01\n" +
	"\x13ResolverInformation\x12=\n" +
	"\fmergeability\x18\x01 \x01(\x0e2\x19.fetchrecord.MergeabilityR\fmergeability\x12\x1a\n" +
	"\bsnippets\x18\x02 \x03(\tR\bsnippets\x124\n" +
	"\n" +
	"strong_ids\x18\x03 \x03(\v2\x15.fetchrecord.StrongIDR\tstrongIds\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\"\xbd\x02\n" +
	"\vProtoEntity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06flavor\x18\x02 \x01(\tR\x06flavor\x123\n" +
	"\tcitations\x18\a \x03(\v2\x15.fetchrecord.CitationR\tcitations\x12k\n" +
	"!named_entity_resolver_information\x18\b \x01(\v2 .fetchrecord.ResolverInformationR\x1enamedEntityResolverInformation\x12`\n" +
	"\x1bflavor_resolver_information\x18\t \x01(\v2 .fetchrecord.ResolverInformationR\x19flavorResolverInformation\"\xad\x01\n" +
	"\x06Record\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12'\n" +
	"\x05atoms\x18\x04 \x03(\v2\x11.fetchrecord.AtomR\x05atoms\x122\n" +
	"\asubject\x18\a \x01(\v2\x18.fetchrecord.ProtoEntityR\asubjectJ\x04\b\x02\x10\x03J\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"\xa2\x03\n" +
	"\x04Atom\x12\x1a\n" +
	"\bproperty\x18\x01 \x01(\tR\bproperty\x12\x1d\n" +
	"\tfloat_val\x18\x04 \x01(\x01H\x00R\bfloatVal\x12\x19\n" +
	"\astr_val\x18\x05 \x01(\tH\x00R\x06strVal\x122\n" +
	"\x06target\x18\f \x01(\v2\x18.fetchrecord.ProtoEntityH\x00R\x06target\x126\n" +
	"\n" +
	"attributes\x18\b \x03(\v2\x16.fetchrecord.AttributeR\n" +
	"attributes\x12\x1c\n" +
	"\ttimestamp\x18\x0e \x01(\x03R\ttimestamp\x123\n" +
	"\tcitations\x18\x10 \x03(\v2\x15.fetchrecord.CitationR\tcitations\x12d\n" +
	"\x1dproperty_resolver_information\x18\x11 \x01(\v2 .fetchrecord.ResolverInformationR\x1bpropertyResolverInformationB\a\n" +
	"\x05valueJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x06\x10\aJ\x04\b\a\x10\b\"\xe4\x01\n" +
	"\tAttribute\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1d\n" +
	"\tstr_value\x18\x05 \x01(\tH\x00R\bstrValue\x12f\n" +
	"\x1eattribute_resolver_information\x18\b \x01(\v2 .fetchrecord.ResolverInformationR\x1cattributeResolverInformationB\r\n" +
	"\vtyped_valueJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03*h\n" +
	"\fMergeability\x12\x1c\n" +
	"\x18MERGEABILITY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MERGEABILITY_MERGEABLE\x10\x01\x12\x1e\n" +
	"\x1aMERGEABILITY_NOT_MERGEABLE\x10\x02B4Z2github.com/example/fido-fetch/internal/fetchrecordb\x06proto3"

var (
	file_fetch_record_proto_rawDescOnce sync.Once
	file_fetch_record_proto_rawDescData []byte
)

func file_fetch_record_proto_rawDescGZIP() []byte {
	file_fetch_record_proto_rawDescOnce.Do(func() {
		file_fetch_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fetch_record_proto_rawDesc), len(file_fetch_record_proto_rawDesc)))
	})
	return file_fetch_record_proto_rawDescData
}

var file_fetch_record_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fetch_record_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_fetch_record_proto_goTypes = []any{
	(Mergeability)(0),           // 0: fetchrecord.Mergeability
	(*SchemaElementMeta)(nil),   // 1: fetchrecord.SchemaElementMeta
	(*FetchMessage)(nil),        // 2: fetchrecord.FetchMessage
	(*StrongID)(nil),            // 3: fetchrecord.StrongID
	(*Citation)(nil),            // 4: fetchrecord.Citation
	(*ResolverInformation)(nil), // 5: fetchrecord.ResolverInformation
	(*ProtoEntity)(nil),         // 6: fetchrecord.ProtoEntity
	(*Record)(nil),              // 7: fetchrecord.Record
	(*Atom)(nil),                // 8: fetchrecord.Atom
	(*Attribute)(nil),           // 9: fetchrecord.Attribute
	nil,                         // 10: fetchrecord.FetchMessage.FlavorMetadataEntry
	nil,                         // 11: fetchrecord.FetchMessage.PropertyMetadataEntry
	nil,                         // 12: fetchrecord.FetchMessage.RelationshipMetadataEntry
	nil,                         // 13: fetchrecord.FetchMessage.AttributeMetadataEntry
}
var file_fetch_record_proto_depIdxs = []int32{
	7,  // 0: fetchrecord.FetchMessage.records:type_name -> fetchrecord.Record
	10, // 1: fetchrecord.FetchMessage.flavor_metadata:type_name -> fetchrecord.FetchMessage.FlavorMetadataEntry
	11, // 2: fetchrecord.FetchMessage.property_metadata:type_name -> fetchrecord.FetchMessage.PropertyMetadataEntry
	12, // 3: fetchrecord.FetchMessage.relationship_metadata:type_name -> fetchrecord.FetchMessage.RelationshipMetadataEntry
	13, // 4: fetchrecord.FetchMessage.attribute_metadata:type_name -> fetchrecord.FetchMessage.AttributeMetadataEntry
	0,  // 5: fetchrecord.ResolverInformation.mergeability:type_name -> fetchrecord.Mergeability
	3,  // 6: fetchrecord.ResolverInformation.strong_ids:type_name -> fetchrecord.StrongID
	4,  // 7: fetchrecord.ProtoEntity.citations:type_name -> fetchrecord.Citation
	5,  // 8: fetchrecord.ProtoEntity.named_entity_resolver_information:type_name -> fetchrecord.ResolverInformation
	5,  // 9: fetchrecord.ProtoEntity.flavor_resolver_information:type_name -> fetchrecord.ResolverInformation
	8,  // 10: fetchrecord.Record.atoms:type_name -> fetchrecord.Atom
	6,  // 11: fetchrecord.Record.subject:type_name -> fetchrecord.ProtoEntity
	6,  // 12: fetchrecord.Atom.target:type_name -> fetchrecord.ProtoEntity
	9,  // 13: fetchrecord.Atom.attributes:type_name -> fetchrecord.Attribute
	4,  // 14: fetchrecord.Atom.citations:type_name -> fetchrecord.Citation
	5,  // 15: fetchrecord.Atom.property_resolver_information:type_name -> fetchrecord.ResolverInformation
	5,  // 16: fetchrecord.Attribute.attribute_resolver_information:type_name -> fetchrecord.ResolverInformation
	1,  // 17: fetchrecord.FetchMessage.FlavorMetadataEntry.value:type_name -> fetchrecord.SchemaElementMeta
	1,  // 18: fetchrecord.FetchMessage.PropertyMetadataEntry.value:type_name -> fetchrecord.SchemaElementMeta
	1,  // 19: fetchrecord.FetchMessage.RelationshipMetadataEntry.value:type_name -> fetchrecord.SchemaElementMeta
	1,  // 20: fetchrecord.FetchMessage.AttributeMetadataEntry.value:type_name -> fetchrecord.SchemaElementMeta
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_fetch_record_proto_init() }
func file_fetch_record_proto_init() {
	if File_fetch_record_proto != nil {
		return
	}
	file_fetch_record_proto_msgTypes[7].OneofWrappers = []any{
		(*Atom_FloatVal)(nil),
		(*Atom_StrVal)(nil),
		(*Atom_Target)(nil),
	}
	file_fetch_record_proto_msgTypes[8].OneofWrappers = []any{
		(*Attribute_FloatValue)(nil),
		(*Attribute_StrValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fetch_record_proto_rawDesc), len(file_fetch_record_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fetch_record_proto_goTypes,
		DependencyIndexes: file_fetch_record_proto_depIdxs,
		EnumInfos:         file_fetch_record_proto_enumTypes,
		MessageInfos:      file_fetch_record_proto_msgTypes,
	}.Build()
	File_fetch_record_proto = out.File
	file_fetch_record_proto_goTypes = nil
	file_fetch_record_proto_depIdxs = nil
}
